collections:
  uvody: 
    output: true
  
  robert_fulghum:
   output: true
 
  petra_soukupova: 
    output: true
  
  harry_potter:
   output: true

  evzen_onegin:
   output: true

  bonus:
   output: true

sass:
    load_paths: 
        - _sass
markdown: kramdown

baseurl: "/knizni_sifra_pro_efi.github.io" 